# Enable DAK processing for this repository
dak:
  enabled: true

# Configure your IG publication details
publication:
  canonical: "http://smart.who.int/trust-phw"
  package_id: "smart.who.int.trust-phw"